### ISSUE TITLE
Create base FastAPI file

### ISSUE THREAD

**Issue by nomomon** [nomomon/text-2-emoji#23]
- [x] Create a file named api.py to serve as the FastAPI implementation
- [x] Make a route (name it like `get_emoji`) that is capable of receiving a string _query_ parameter named `text` and returns a dictionary emoji to number. For the meantime, make all numbers 0.
  - The emojis can be found in the `mapping.csv`

**Comment by nomomon** [comment]
https://fastapi.tiangolo.com/tutorial/first-steps/

https://fastapi.tiangolo.com/features/

**Comment by pykrishna** [comment]
I updated the as required. How to contribute ?

**Comment by nomomon** [comment]
> I created the code as required. How to contribute ?

Hi @pykrishna, thank you for checking out our project! Unfortunately, it is a project for a university course and the teaching assistant (@O-T-O-Z) did not allow it.

**Comment by pykrishna** [comment]
No problem.

Thanks for replying
